package:
  name: rasterio
  version: "0.15.1"

source:
  git_tag: "0.15.1"
  git_url: https://github.com/mapbox/rasterio.git
#  patches:
   # List any patch files here
   # - fix.patch

build:
  number: 0
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pyshp = pyshp:main
    #
    # Would create an entry point called pyshp that calls pyshp.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1


  entry_points:
    - rio = rasterio.rio.main:cli

requirements:
  build:
    - affine >=1.0
    - cython >=0.20
    - click
    - enum34
    - gdal
    - numpy >=1.8
    - python
    - setuptools

  run:
    - affine >=1.0
    - click
    - enum34
    - gdal
    - numpy >=1.8
    - python

test:
  imports:
    - rasterio

about:
  home: https://github.com/mapbox/rasterio
  license: BSD

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
