package:
  name: coveralls
  version: !!str 0.5

source:
  fn: coveralls-0.5.zip
  url: https://pypi.python.org/packages/source/c/coveralls/coveralls-0.5.zip
  md5: 9830c7ec568b2ffde62e9dabbcecfbba
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - coveralls = coveralls:main
    #
    # Would create an entry point called coveralls that calls coveralls.main()

    - coveralls = coveralls.cli:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pyyaml >=3.10
    - docopt >=0.6.1
    - coverage >=3.6,<3.999
    - requests >=1.0.0

  run:
    - python
    - pyyaml >=3.10
    - docopt >=0.6.1
    - coverage >=3.6,<3.999
    - requests >=1.0.0

test:
  # Python imports
  imports:
    - coveralls

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - coveralls --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/coagulant/coveralls-python
  license: MIT License
  summary: 'Show coverage stats online via coveralls.io'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
