package:
  name: geos
  version: 3.4.2

source:
  fn: geos-3.4.2.tar.gz
  url: http://download.osgeo.org/geos/geos-3.4.2.tar.bz2
  md5: fc5df2d926eb7e67f988a43a92683bae

requirements:
  build:
    - python
  run:
    - python

about:
  home: http://trac.osgeo.org/geos/
  license: LGPL
